### ISSUE TITLE
CFG: Simulate for Testing

### ISSUE THREAD

**Issue by edilsalvador** [PLMCSIT/LexiCom#15]
Program 1:
Start on Production No. 124:

```
If !((price@tax >= 0.24)&&!(exceed(price@tax; 0.12)))
    Say ("Your tax: ", price@tax, " is over taxing!").
    Say ("Please report this to the officials...").
Or ((checktax(price@tax; 0.12) * 100) == 12)
    Say ("Your tax: ", price@tax, " is just right!").
    Say ("Thank you!").
EndIf.
```

Program 2:
Start on Production No. 124:

```
If(Yes)

  If(Yes)
      Var result is No as Boolean.

      If(!result)
      Otherwise
      EndIf.

  Otherwise
  EndIf.

Otherwise
EndIf.
```

Program 3:
Start on Production No. 126:

```
Option paul@age
Start
  State 30:
      Say("You're old!").
  Stop.
  State 40:
     Say("You're too old!").
  Stop.
End.
```

**Comment by edilsalvador** [comment]
STATUS UPDATE:
- Will merge pull request #11 soon and start resolving issues #12 , #14 , #13 and #2.

**Comment by edilsalvador** [comment]
**Minor bugs found:**

```
on <vardec>.
fixed by updating <vardec> with:
<vardec>    ->    Var id <vardec_init>.
<vardec_init>    ->    <init>
<vardec_init>    ->    as <dtype>
```

Will add another commit to pull request #11.

**Comment by edilsalvador** [comment]
**Minor issue found:**
`No null terminator on <if3>.`

Waiting for the result of simulation.
Please comment the result here --- @shinzangetsu.

**Comment by shinzangetsu** [comment]
Simulations for Testing Complete.

Simulations:
PROGRAM 1: PASSED
PROGRAM 2: PASSED
PROGRAM 3: PASSED

CFG is able to produce all three programs

**Comment by edilsalvador** [comment]
SIMULATION PASSED!
Will upload the final commit for CFG.
