### ISSUE TITLE
TD: Misleading Flow on For TD (Reserved Symbols)

### ISSUE THREAD

**Issue by edilsalvador** [PLMCSIT/LexiCom#20]
Misleading Flow on For TD (Reserved Symbols) on States: 190 - 201.
- Incapable on reading single symbols like "=" and "!".
- Misleading flow for "<" and ">".

`When reading input "<" or ">", it will lead to invalid input because it will automatically go to state 196 or state 199 respectively and will not go to state 214 or state 216.`

**Comment by clinomania** [comment]
Sa master ba eedit ko? Wala kasing branch for trans diag

**Comment by edilsalvador** [comment]
@clinomania sa refactor-finalized docu na branch mo i-edit.

**Comment by clinomania** [comment]
Di pa ba to closed dapat? :yum:
