### ISSUE TITLE
LEXICOM: Intlit and Doublelit For Testing

### ISSUE THREAD

**Issue by edilsalvador** [PLMCSIT/LexiCom#24]
Please be guided that the Integer literal and Double literal Analyzer is now up for testing.

Here are simple rules for testing:

For Integer Literal:
- Test possible delimiters provided on the Transitional Diagram

For Double Literal:
- Test possible delimiters provided on the Transitional Diagram
- Multiple decimal points results to a valid doublelit for the first instance. (e.g. 192.168.1 -> 192.168 is valid, '.' is invalid and 1 is an intlit.)

NOTE: Please do refer to the transitional diagram flow. Thanks :smile:

**Comment by clinomania** [comment]
In reference sa #23 and #21 din na issue, eto yung probs. Pag-isahin ko na lang sa isang comment.

#.1 Sample code: Var X as Int is 3. 
-------Prob 1: Nababasa as decimal point yung terminator na period kaya sa lexical ang token niya is _doublelit_ pero dapat talaga intlit yun. Pag nilagyan ng space tho, nagiging intlit na siya.
-------Prob 2: kasama sa token ng id yung 'as' after ng 'X'. Bale yung lexeme is 'X as' pero ang token is id in which dapat hindi.
#.2 Sample code: Var Dan as Int is 0.098.455.4.5.4.
-------Prob 1: Dapat yung unang doublelit lang mababasa, the rest error na. Diyan kasi sa example yung mga susunod na instances nababasa as doublelit.
#.3 Sample code: Task Dan(Var A as Int).
-------Prob 1: kulang delim ng data types kasi dito nag-invalid yung Int kahit hindi naman dapat. Dapat kasama sa delim yung close parenthesis.
#.4 Sample code: Var Dan as Int is 4 "r" 3.14 'd' .
-------Prob 1: Dapat isang value lang acccepted. tho parang pwede na ata sa syntax error to.
#.5 Sample code: Var Dan as Char is 'dan'.
-------Prob 1: Specify sa error kung ano yung error talaga, like saang line number at anong lexeme yung may error. Kasi example yung error sa ##2 sample code is isa sa error ng Var Dan as Char is 'dan'
#.6 Sample code: Var Dan as Char is 3 ".
-------Prob 1: Hindi dapat magkasama, I mean hindi dapat iisang lexeme yung ". kasi nung nirun magkasama sila tapos invalid yung token.
#.7 Sample code: Say Str1, "hellow",  H, 3.14, '4', "checked by dan".
-------Prob 1: yung concatenation, kelangan pala may space para maread yung next kasi sa docu wala space. Specify sa rules na need ng space kapag nagcconcatinate sa 'Say'. Tapos yung H natreat as id.

Other notes:
-------1] Specify sa rule na need ng space para sa multiple declarations or ayusin yung delimeters.
-------2] Bakit sa array tama naman yung Other notes no. 1? Kaso invalid nilabas hindi intlit. (Sample code: Array of 3 by 2 Nums as Int is 1.2 ; 2.3 ; 3.)
-------3] Pano declaration nung int i = 0 sa loob? Tama ba to? (for(int i = 0; i<1;i++)) 
-------4] AYUSIN NIYO RULES NIYO UTANG NA LOOB!! iba delim ng task lead niyo docu at lexical baka pati yung iba mali. pa check //clinomania: di ako yung bossy na to ah. Si QA yun. Sorry na edil xD

QA: Limense, Dan Aaron M.
Sexytary: clinomania ♥

**Comment by shinzangetsu** [comment]
1. "Specify sa rule na need ng space para sa multiple declarations or ayusin yung delimeters."
2. " AYUSIN NIYO RULES NIYO UTANG NA LOOB!! iba delim ng task lead niyo docu at lexical baka pati yung iba mali. pa check" 
3. and other cases regarding delimiter errors

@clinomania
Under the NOTES of the previous commits made, it was cited specifically that "Some delimiters are still inappropriate. Need to change accordingly."

**Comment by edilsalvador** [comment]
Thank you pala sa pagsimulate ng lexical :+1: Pero intlit at doublit lang pinapatest ko dito kasi alam kong madaming mali sa reserved words at symbols kasi hindi pa updated yung delimiters :smile:

**Comment by edilsalvador** [comment]
#.1 Sample code: Var X as Int is 3. 
-------Prob 1: Fixed
-------Prob 2: Fixed

#.2 Sample code: Var Dan as Int is 0.098.455.4.5.4.
-------Prob 1: No Issues (as what indicated on the Transitional Diagram, the error handling is just right)

#.3 Sample code: Task Dan(Var A as Int).
-------Prob 1: No Issues (improper construction of Sample Code, as to the updated delimiter for data types it only allows whitespace, period and colon).

#.4 Sample code: Var Dan as Int is 4 "r" 3.14 'd' .
-------Prob 1: No Issue (All input was valid for Lexical Analysis, Code Structure Errors are for Syntax Analysis).

#.5 Sample code: Var Dan as Char is 'dan'.
-------Prob 1: Fixed.

#.6 Sample code: Var Dan as Char is 3 ".
-------Prob 1: No Issue (Unclosed String Literal is considered as one error)

#.7 Sample code: Say Str1, "hellow", H, 3.14, '4', "checked by dan".
-------Prob 1: Fixed. (as per concatenation. H is considered as a valid Identifier as stated in the rules.) ----------Sample Code Error: Only Id, String and Character literals can be concatenated.

Other notes:
-------1] Fixed as per the Lexical Analyzer.
-------2] Fixed.
-------3] No Issue (Refer to CFG)
-------4] No Issue (Previous Delimiters are created by @clinomania  and @shinzangetsu) sa kanila ka magalit Dan huwag sakin. HAHAHA.

LEXICAL ANALYZER PASSED! WOHOOOOO!
