### ISSUE TITLE
LEXICOM: Language Overview, General Rules and Structure Overview

### ISSUE THREAD

**Issue by clinomania** [PLMCSIT/LexiCom#33]
- [x] I. Language Overview (Eto yung about lang sa Compiler)
- [x] II. General Rules (Rules about case sensitivity, Start/ End, Comments, Declaration, Terminator, etc.. Lahat yan Pang-general lang talaga na rules.
- [x] III. Structure Overview (Structure tapos konting about about sa parts nung structure)

**Comment by edilsalvador** [comment]
Oks na ba to? @clinomania

**Comment by clinomania** [comment]
yup. oks na yan xD

**Comment by clinomania** [comment]
Commited

**Comment by clinomania** [comment]
adib adib ako na nagclose XD

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In progress](https://trello.com/c/KwAJ1Zw5/5-in-progress)
