### ISSUE TITLE
LEXICOM: Specific Rules

### ISSUE THREAD

**Issue by clinomania** [PLMCSIT/LexiCom#34]
Specific Rules
- [x] Identifiers
- [x] Data Types (Valid/Invalid)
- [x] Literals
- [x] Variables
- [x] Constant
- [x] Array
- [x] Operators
- [x] Operator Precedence.
- [x] Expression (Mathematical, Conditional, Logical)
- [x] Statements (Assignment, I/O, Conditional, Looping, Function, Structure)

Note: Yung ibang meron na kelangan din i-revise, pa-revise :D

**Comment by clinomania** [comment]
Yung comments no no no no no check na yun forever?

**Comment by edilsalvador** [comment]
24 hours no no no no no check na yun :smiley:

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In progress](https://trello.com/c/KwAJ1Zw5/5-in-progress)

**Comment by clinomania** [comment]
pwede na iclose
