### ISSUE TITLE
TEST SCRIPTS: Lexical Analyzer

### ISSUE THREAD

**Issue by clinomania** [PLMCSIT/LexiCom#35]
Test the following including all its valid and 5 invalid delimiters:
- [x] Reserved Words
- [x] Reserved Symbols
- [x] Identifiers
- [x] Literals

Note: Refer to the Transitional Diagram

**Comment by edilsalvador** [comment]
Removing that pain in the ass Comments.

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ready](https://trello.com/c/zmyWlFDn/2-ready)

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ready](https://trello.com/c/zmyWlFDn/2-ready)
