### ISSUE TITLE
DEBUG

### ISSUE THREAD

**Issue by shinzangetsu** [PLMCSIT/LexiCom#43]
- [x] Issue 1:
  Reserved words: "Yes" and "No" still aren't defined as "boollit" in the compiler.
- [x] Issue 2:
  "-=" "+=" "*=" "/=" and "%=" should not be defined as token because our compiler doesn't have those kind of reserved symbols.

**Comment by shinzangetsu** [comment]
DEBUG 003: The input 1+3%5 produces an error. The numbers are missing a delimiter " % "

**Comment by edilsalvador** [comment]
Will close this. :+1:

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Done](https://trello.com/c/UFWVo8ag/6-done)
